FROM apache/airflow:2.10.4

WORKDIR /opt/airflow
ENV AIRFLOW_HOME=/opt/airflow

RUN pip install --upgrade pip && \
    # pip install apache-airflow-providers-apache-spark && \
    pip install apache-airflow-providers-apache-livy && \ 
    pip install psycopg2-binary